main: alex231.minecraft.minecord.MinecordPlugin
name: Minecord
version: 0.3
author: alex231
description: Connects Minecraft and Discord chat.
commands:
  minecord:
    description: Test command. Ping!
    usage: /minecord
    permission: minecord.minecord
    permission-message: You don't have permission to use this command.